import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
import { NotifierProvider } from "@/components/Notifier/NotifierProvider";
import { Header } from "@/components/Header/Header";
import { CartProvider } from "@/context/CartContext";
import { FooterCart } from "@/components/Footer/FooterCart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CartProvider>
            <NotifierProvider/>
            <Header/>
            <main>
              {children}
            </main>
            <footer className="fixed bottom-0 w-full">
              <FooterCart/>
            </footer>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
